# Generated by Django 4.2.6 on 2023-10-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='YearRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='collections',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
