# Generated by Django 4.2.6 on 2023-10-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GB', '0003_bonus_distrate_energierate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='passager',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
