# Generated by Django 4.2.6 on 2023-10-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GB', '0005_rename_rate_bonus_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='bonus',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='passager',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='distrate',
            name='end_dist_fin',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='distrate',
            name='start_dist',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='yearrate',
            name='end_year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='yearrate',
            name='start_year',
            field=models.IntegerField(default=2010),
        ),
    ]
