# Generated by Django 4.2.6 on 2023-10-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GB', '0006_alter_bonus_bonus_alter_bonus_passager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrate',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energierate',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='typerate',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='yearrate',
            name='rate',
            field=models.FloatField(),
        ),
    ]
