# Generated by Django 4.2.6 on 2023-10-31 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GB', '0007_alter_distrate_rate_alter_energierate_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distrate',
            old_name='end_dist_fin',
            new_name='end_dist',
        ),
    ]
