# Generated by Django 4.2.6 on 2023-10-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GB', '0009_tauxemprunt_rename_end_dist_distrate_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tauxemprunt',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
