# Generated by Django 4.2.6 on 2023-10-31 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GB', '0010_tauxemprunt_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energierate',
            old_name='energie',
            new_name='type',
        ),
    ]
